hostname = 'stretch-icinga2a'
box = 'debian/stretch64'
net = 'demo.local'
hostonly = '172.16.33.5'
memory = '2048'
cpus = '2'

Vagrant.configure(2) do |config|
  config.vm.box = box
  config.vm.hostname = hostname
  config.vm.network :private_network, ip: hostonly,
    nic_type: "82540EM"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.name = hostname
    vb.customize ["modifyvm", :id,
      "--groups", "/Icinga 2 Vagrant/" + net,
      "--memory", "512",
      "--cpus", "1",
      "--audio", "none",
      "--usb", "on",
      "--usbehci", "off",
      "--natdnshostresolver1", "on"
    ]
    vb.cpus = cpus
    vb.memory = memory
  end

  config.vm.provision "shell", path: "../scripts/shell_provisoner.sh"
end
