hostname = 'srv-icinga2'
box = 'debian/jessie64'
net = 'demo.local'
hostonly = '192.168.16.5'
memory = '2048'
cpus = '2'

Vagrant.configure(2) do |config|
  config.vm.box = box
  config.vm.hostname = hostname
  config.vm.network :private_network, ip: hostonly
  # config.vm.network "forwarded_port", guest: 22, host: 2082

  config.vm.provider "virtualbox" do |vb|
    vb.name = hostname
    vb.customize ["modifyvm", :id,
      "--groups", "/Icinga 2 Vagrant/" + net,
      "--memory", "512",
      "--cpus", "1",
      "--audio", "none",
      "--usb", "on",
      "--usbehci", "off",
      "--natdnshostresolver1", "on"
    ]
    vb.cpus = cpus
    vb.memory = memory
  end

  # config.vm.provision "shell", inline: "service networking restart", run: "always"

  config.vm.provision "shell", path: "./scripts/shell_provisoner.sh"

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "./playbooks/playbook.yml"
    ansible.install_mode = "pip"
    ansible.version = "2.3.1.0"
  end
end
